### ISSUE TITLE
Star Wars Problem

### ISSUE THREAD

**Issue by IsaacRoss** [ThornWinter/Training#4]
I looked at your code and you are very much on the right path. One problem is that the url is wrong, which is probably a typo, you have an extra http in there.  The other problem is that JSON parse will parse the JSON representation into a javascript object. That means you have to look at it carefully to see how the request is formed. The response from the star wars api are a few properties that describe the resultset, like count, and the url where you can get the next batch (it's paged) and then a results propery, which is the actual array of results.  I took a screen shot in my console of what the object looks like.

<img width="836" alt="screen shot 2015-12-14 at 7 09 05 am" src="https://cloud.githubusercontent.com/assets/2347063/11780734/384944b0-a232-11e5-8ed2-b04d7d458fc3.png">

That should get you to the end, and then we'll discuss DOM operation improvements.

**Comment by ThornWinter** [comment]
I just almost jizzed in my pants when I finally printed out the first page. It's ugly but it works....lol...I assume I'll have to drop in another loop to loop through the pages and print the remaining planets out but I'm going to celebrate getting more than a white fucking screen. Thanks dude. I really needed this win. Going to dive back in and try to get the next page working as well...FUCK YEAH. Oh, also, am I using GitHub correctly??? I know I type fuck alot but in general am I following "ettiquette".
